# Версия docker-compose
version: '3'
# Список наших сервисов (контейнеров)
services:
    php:
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./docker/php
        container_name: ${DOCKER_PROJECT_PREFIX}php
        environment:
            PROJECT_DATABASE_PATH: ${PROJECT_DATABASE_PATH}
            PROJECT_BACKUP_NAME_DB: ${PROJECT_BACKUP_NAME_DB}
            PROJECT_BASIC_AUTH_LOGIN: ${PROJECT_BASIC_AUTH_LOGIN}
            PROJECT_BASIC_AUTH_PASSWORD: ${PROJECT_BASIC_AUTH_PASSWORD}
        ports:
            - '${DOCKER_PHP_PORT}:9000'
        volumes:
            - ./public:/var/www:rw
            - ./docker/logs/php:/var/log/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        networks:
            - backend
        restart: always

    mysql:
        build: ./docker/mysql
        container_name: ${DOCKER_PROJECT_PREFIX}mysql
        command: mysqld --user=mysql --default-authentication-plugin=mysql_native_password
        volumes:
            - ./public:/var/www:rw
            - ./docker/data/mysql:/var/lib/mysql:rw
            - ./install/db/mysql.backup.sql:/docker-entrypoint-initdb.d/mysql.backup.sql
            - ./docker/logs/mysql:/var/log/mysql
        ports:
            - '${DOCKER_MYSQL_PORT}:3306'
        # задаем пароль для root пользователя
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
        networks:
            - backend
        restart: always

    nginx:
        # используем последний стабильный образ nginx
        image: nginx:latest
        container_name: ${DOCKER_PROJECT_PREFIX}nginx
        volumes:
            - ./public:/var/www:rw
            - ./docker/logs/nginx:/var/log/nginx
            - ./docker/nginx:/etc/nginx/conf.d
            - ./docker/certs:/etc/ssl/certs
        # маршрутизируем порты
        ports:
            - "${DOCKER_NGINX_PORT}:80"
            - "${DOCKER_SSL_PORT}:443"
        # nginx должен общаться с php контейнером
        links:
            - php
            - mysql
        networks:
            - backend
        restart: always

networks:
    backend:
        driver: bridge
